# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 153049af00e81bbd70cbf39fd93ceffe58918590ae7c22e523cbbb0c8595d0cafa9d007a75863fcfeae04a9211342c4d56aceaec57089bfe60ed129209bc7bfb

test:
  secret_key_base: 89a8e79297e7f739a900a8a99f3152871a1317a21abb29e3de5cc993db5e0b0aac169ba4bade05e4069fa7abced62eb20ca126888731064e9bc9ce605ab72abd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
